#!/usr/bin/env python3
"""Regenerate fusion/docs/PARAMETERS.md from params.py.

The parameter reference is generated rather than written so it cannot drift
from the code. Re-run it after adding or renaming a User Parameter:

    python3 fusion/tests/gen_parameter_doc.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "OgmaBowl"))
sys.path.insert(0, str(Path(__file__).parent))

from smoke_imports import install_stub  # noqa: E402

install_stub()

from ogma_bowl import params  # noqa: E402
from ogma_bowl import styles  # noqa: E402

HEADER = """# Parameter reference

Every value below appears in Fusion under **Modify > Change Parameters**. Type
a new number, press Enter, and the timeline rebuilds.

They all carry the `ogma` prefix so they sort together and cannot collide with
anything you add by hand. Lengths are millimetres; counts and percentages are
unitless.

Rows written as an expression rather than a number are *derived* — edit what
they reference, not them, or you break the link.

> Generated by `fusion/tests/gen_parameter_doc.py`. Do not edit by hand.

"""

TABLE_HEAD = (
    "| Parameter | Default | Unit | What it does |\n"
    "|---|---|---|---|\n"
)


def rows(table):
    out = []
    for name, expression, unit, comment in table:
        out.append("| `{}` | `{}` | {} | {} |".format(
            name, expression, unit or "-", comment))
    return "\n".join(out)


def main() -> int:
    parts = [HEADER]

    parts.append("## Shared — created for every style\n\n")
    parts.append(TABLE_HEAD + rows(params.SHARED) + "\n\n")

    for style_id in styles.STYLE_IDS:
        module = styles.get(style_id)
        parts.append("## {} (`{}`)\n\n".format(module.LABEL, style_id))
        parts.append(TABLE_HEAD + rows(params.STYLE_TABLES[style_id]) + "\n\n")

    parts.append(
        "## Values that are NOT parameters\n\n"
        "A few things are structural rather than dimensional, and changing "
        "them needs the command re-run rather than a parameter edit:\n\n"
        "- **the letters themselves** — the name is text, and Fusion User "
        "Parameters are numeric. Re-run **Ogma Bowl** to change it.\n"
        "- **honeycomb column count** — derived from `ogmaHexCellRadius` and "
        "then quantised to an even number, so small edits to the cell radius "
        "may not change the pattern at all.\n"
        "- **the wave sine seam** — sampled into splines at build time. "
        "`ogmaWaveAmp` and `ogmaWaveCount` are recorded as parameters for "
        "reference, but the seam surface only picks them up on a re-run.\n"
    )

    out_path = ROOT / "docs" / "PARAMETERS.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("".join(parts))

    total = len(params.SHARED) + sum(
        len(params.STYLE_TABLES[s]) for s in styles.STYLE_IDS
    )
    print("wrote {} ({} rows across {} styles)".format(
        out_path, total, len(styles.STYLE_IDS)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
