"""Building one style must not change what the next style builds.

The generator configures itself through module globals. `jobs.py` serialises
builds behind a lock so two cannot interleave, and that is necessary — but it is
not sufficient. Serialising stops two builds running *at once*; it does nothing
about one build leaving its settings behind for the next.

That gap shipped. The honeycomb, fluted drum and wave each overwrite
NAME_RAIL_OUTER_R / LETTER_FACE_R / LETTER_CENTER_Z with their own wall radius
and never restore them. The paw lattice is the one style that sets none of them,
so it inherited whatever ran last: its letters were built for an 81.6 mm wall
and placed on its own 86 mm one, ending up buried inside the drum.

**The golden harness cannot catch this.** `goldens.py` runs each case in a fresh
subprocess, so every build there starts from a clean module — exactly the
condition the API server does not provide. These tests run the builds in ONE
process, which is what the server does.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
for _p in (REPO / "products" / "dog-bowl" / "generator", REPO / "shared"):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

import cooper_bowl_design as design  # noqa: E402
import styles  # noqa: E402

# The globals a style may overwrite. Kept explicit: if a style starts mutating a
# fourth, this list should grow with it.
LEAKY = ("NAME_RAIL_OUTER_R", "LETTER_FACE_R", "LETTER_CENTER_Z")


def _snapshot() -> dict[str, float]:
    return {k: getattr(design, k) for k in LEAKY}


@pytest.fixture(autouse=True)
def _clean_module():
    """Every test starts from the paw lattice's defaults."""
    design.reset_letter_geometry()
    yield
    design.reset_letter_geometry()


def test_configure_output_restores_the_defaults(tmp_path):
    """The reset happens on the call every style makes first."""
    defaults = _snapshot()

    design.NAME_RAIL_OUTER_R = 1.0
    design.LETTER_FACE_R = 2.0
    design.LETTER_CENTER_Z = 3.0

    design.configure_output(tmp_path, name="MAX", font_style="bold")
    assert _snapshot() == defaults


@pytest.mark.parametrize("first", ["hex", "fluted", "wave"])
def test_a_previous_style_does_not_move_the_paw_lattice_rail(first, tmp_path):
    """The exact sequence that buried the letters: drum style, then cooper.

    Asserted on the rail geometry rather than on a built mesh, so the test is
    fast and names the quantity that was wrong.
    """
    defaults = _snapshot()

    # Build-time configuration for the first style, the way its own
    # generate_meshes does it.
    styles.get(first)  # the style must exist
    design.configure_output(tmp_path / first, name="MAX", font_style="bold")
    if first == "hex":
        import hex_bowl_design as m
        m._configure_hex_letters()
    elif first == "fluted":
        import fluted_bowl_design as m
        m._configure_fluted_letters()
    else:
        import wave_bowl_design as m
        m._configure_wave_letters()

    moved = _snapshot()
    assert moved != defaults, (
        f"{first} was expected to override the rail geometry; if it no longer "
        "does, this test is no longer testing anything"
    )

    # Now the paw lattice, which sets none of these itself.
    design.configure_output(tmp_path / "cooper", name="MAX", font_style="bold")
    assert _snapshot() == defaults, (
        f"building {first} first left its rail geometry behind: the paw "
        f"lattice would place letters at R={design.LETTER_FACE_R} instead of "
        f"{defaults['LETTER_FACE_R']}"
    )


def test_letters_land_on_the_wall_they_were_built_for(tmp_path):
    """End to end, in one process — the shape of the actual bug.

    Builds the honeycomb, then the paw lattice, and checks cooper's letters sit
    against cooper's rail rather than inside the drum.
    """
    import hex_bowl_design  # noqa: F401

    hex_style = styles.get("hex")
    hex_style.generate_meshes(tmp_path / "hex", "MAX", "bold")

    cooper = styles.get("cooper")
    cooper.generate_meshes(tmp_path / "cooper", "MAX", "bold")

    import numpy as np
    import trimesh

    letter = trimesh.load_mesh(tmp_path / "cooper" / "meshes" / "assembly_letter_1_M.stl")
    r = np.hypot(letter.vertices[:, 0], letter.vertices[:, 1])
    rail = design.NAME_RAIL_OUTER_R

    # Checked against the panel that was actually built, not against the
    # constants the letter was built from. The letter and its pocket are
    # generated by different functions, and the failure this test exists for is
    # exactly the case where those two disagree — so recomputing the expected
    # radius from LETTER_POCKET_DEPTH would ask the implementation to mark its
    # own homework.
    panel = trimesh.load_mesh(tmp_path / "cooper" / "meshes" / "assembly_paw_panel.stl")
    pv = panel.vertices
    plaque = (
        (pv[:, 1] < -80.0)
        & (np.abs(pv[:, 0]) < 32.0)
        & (pv[:, 2] > 33.0)
        & (pv[:, 2] < 48.0)
    )
    pocket_floor = float(np.hypot(pv[plaque, 0], pv[plaque, 1]).min())

    # Flush. The letters sit *in* the rail, not on it — a proud edge is a dirt
    # trap on something that gets washed. See LETTER_PROUD.
    assert r.max() == pytest.approx(rail, abs=0.05), (
        f"letter face at R={r.max():.2f} is not flush with the {rail:.2f} rail"
    )
    # And it seats on that floor rather than bottoming out or floating: the gap
    # under the back is the glue line.
    clearance = r.min() - pocket_floor
    assert 0.0 <= clearance <= 0.25, (
        f"letter back at R={r.min():.2f} vs pocket floor R={pocket_floor:.2f} "
        f"— clearance {clearance:.3f} mm is not a glue gap"
    )
